[package]
name = "checkle"
version = "0.1.0"
edition = "2021"
license = "MIT"
readme = "README.md"
description = "Extremely fast checksum runner for arbitrarily large batches of files"
repository = "https://github.com/nrminor/checkle"
homepage = "https://github.com/nrminor/checkle"
documentation = "https://github.com/nrminor/checkle/blob/main/README.md"
keywords = ["science", "reproducibility", "bioinformatics", "data"]
categories = ["command-line-utilities", "science"]

[[bin]]
name = "checkle"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.3", features = ["derive", "cargo"]}
clap-verbosity-flag = "2.1.1"
displaydoc = "0.2.4"
sha2 = "0.10.8"
base64ct = "1.6.0"
color-eyre = "0.6.3"
rayon = "1.10.0"
digest = "0.10.7"
md-5 = "0.10.6"
thiserror = "2.0.12"
fern = { version = "0.7.1", features = ["colored"] }
log = "0.4.27"
indicatif = { version = "0.17.11", features = ["rayon"] }
jiff = { version = "0.2.6", features = ["logging"] }

[profile.dev]
incremental = true
lto = false

[profile.release]
lto = "fat"
opt-level = "z"
codegen-units = 1
incremental = true
panic = "abort"
strip = "symbols"

[dev-dependencies]
pretty_assertions = "1.4.1"
sccache = "0.10.0"
tempfile = "3.19.1"

